package me.sebz.mu.pbl5;

import com.codename1.system.Lifecycle;
import com.codename1.ui.Button;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Dialog;
import com.codename1.ui.Display;
import com.codename1.ui.FontImage;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.TextArea;
import com.codename1.ui.TextField;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.BoxLayout;
import me.sebz.mu.pbl5.net.NetworkClient;

/**
 * This file was generated by Codename One for building native mobile applications using Java.
 */
public class MemoryLens extends Lifecycle {

    private static final String TITLE_ERROR = "Error";
    private static final String ROLE_DEFAULT_FAMILY = "2";
    private static final String ROLE_ADMIN = "ADMIN";
    private static final String ROLE_PATIENT = "PATIENT";

    private static String sessionToken;
    private static Long memberId;
    private static Long familyGroupId;
    private static String userRole;
    private static String chatId;
    private static boolean hasEmbedding;

    public static boolean hasEmbedding() {
        return hasEmbedding;
    }

    public static void setHasEmbedding(boolean value) {
        hasEmbedding = value;
    }

    public static String getSessionToken() {
        return sessionToken;
    }

    public static void setSessionToken(String token) {
        sessionToken = token;
    }

    public static Long getMemberId() {
        return memberId;
    }

    public static void setMemberId(Long id) {
        memberId = id;
    }

    public static Long getFamilyGroupId() {
        return familyGroupId;
    }

    public static void setFamilyGroupId(Long id) {
        familyGroupId = id;
    }

    public static String getUserRole() {
        return userRole;
    }

    public static void setUserRole(String role) {
        userRole = role;
    }

    public static String getChatId() {
        return chatId;
    }

    public static void setChatId(String value) {
        chatId = value;
    }

    public static void navigateToAppropriateDashboard() {
        Display.getInstance().callSerially(() -> {
            if (familyGroupId == null) {
                new GroupOnboardingForm().show();
                return;
            }

            DashboardTarget target = determineDashboardTarget(userRole);
            showDashboard(target);
        });
    }

    private enum DashboardTarget {
        ADMIN, PATIENT, FAMILY
    }

    private static DashboardTarget determineDashboardTarget(String role) {
        String roleShort = (role != null) ? role : ROLE_DEFAULT_FAMILY;

        if (isAdminRole(roleShort)) {
            return DashboardTarget.ADMIN;
        }
        if (isPatientRole(roleShort)) {
            return DashboardTarget.PATIENT;
        }
        return DashboardTarget.FAMILY;
    }

    private static boolean isAdminRole(String roleShort) {
        return roleShort.startsWith("0") || ROLE_ADMIN.equalsIgnoreCase(roleShort);
    }

    private static boolean isPatientRole(String roleShort) {
        return roleShort.startsWith("1") || ROLE_PATIENT.equalsIgnoreCase(roleShort);
    }

    private static void showDashboard(DashboardTarget target) {
        switch (target) {
            case ADMIN:
                new AdminDashboard().show();
                break;
            case PATIENT:
                new PatientDashboard().show();
                break;
            default:
                new FamilyDashboard().show();
                break;
        }
    }

    @Override
    public void runApp() {
        showLoginScreen();
    }

    public static void logout() {
        showLoginScreen();
    }

    public static void showLoginScreen() {
        Form loginForm = new Form("Login", new BorderLayout());

        Container center = new Container(BoxLayout.y());
        center.setScrollableY(true);
        center.getAllStyles().setPadding(10, 10, 10, 10);

        Label title = new Label("MemoryLens");
        title.setUIID("Title");
        title.getAllStyles().setAlignment(Component.CENTER);
        title.getAllStyles().setMarginBottom(10);

        TextField emailField = new TextField("", "Email", 20, TextArea.EMAILADDR);
        emailField.setUIID("TextField");

        TextField passwordField = new TextField("", "Password", 20, TextArea.PASSWORD);
        passwordField.setUIID("TextField");

        Button loginButton = new Button("Login");
        loginButton.setMaterialIcon(FontImage.MATERIAL_LOGIN, 5);

        Button registerButton = new Button("Register");
        registerButton.setUIID("ButtonSecondary");
        registerButton.setMaterialIcon(FontImage.MATERIAL_PERSON_ADD, 5);
        registerButton.addActionListener(e -> new RegistrationForm().show());

        loginButton.addActionListener(e -> {
            String email = emailField.getText();
            String password = passwordField.getText();

            if (email.isEmpty() || password.isEmpty()) {
                Dialog.show(TITLE_ERROR, "Please fill all fields", "OK", null);
                return;
            }

            if (!email.contains("@") || !email.contains(".")) {
                Dialog.show("Invalid Email", "Please enter a valid email address", "OK", null);
                return;
            }

            java.util.Map<String, Object> loginData = new java.util.HashMap<>();
            loginData.put("email", email);
            loginData.put("password", password);

            GenericNetworkService.getInstance().post("/api/auth/login", loginData,
                    new NetworkClient.Callback() {
                        @Override
                        public void onSuccess(java.util.Map<String, Object> response) {
                            System.out.println("DEBUG: Login Response: " + response); // ignored logger issue

                            String roleShort = String.valueOf(response.get("role"));
                            String token = (String) response.get("session");

                            Long fgId = asLong(response.get("familyGroupId"));
                            Long mId = asLong(response.get("memberId"));

                            boolean hasEmb = parseBoolean(response.get("hasEmbedding"));

                            MemoryLens.setSessionToken(token);
                            MemoryLens.setFamilyGroupId(fgId);
                            MemoryLens.setMemberId(mId);
                            MemoryLens.setUserRole(roleShort);
                            MemoryLens.setHasEmbedding(hasEmb);

                            Object chat = response.get("chatId");
                            if (chat != null) {
                                MemoryLens.setChatId(String.valueOf(chat));
                            }

                            System.out.println("DEBUG: Navigating to dashboard with Role: " + roleShort + ", GroupID: " + fgId);
                            MemoryLens.navigateToAppropriateDashboard();
                        }

                        @Override
                        public void onFailure(String errorMessage) {
                            Display.getInstance().callSerially(() ->
                                    Dialog.show("Login Failed", errorMessage, "OK", null)
                            );
                        }
                    });
        });

        center.add(title);
        center.add(new Label("Welcome Back"));
        center.add(emailField);
        center.add(passwordField);
        center.add(loginButton);
        center.add(registerButton);

        loginForm.add(BorderLayout.CENTER, center);
        loginForm.show();
    }

    private static Long asLong(Object value) {
        if (value instanceof Number) {
            return ((Number) value).longValue();
        }
        return null;
    }

    private static boolean parseBoolean(Object value) {
        if (value instanceof Boolean) {
            return (Boolean) value;
        }
        return value != null && Boolean.parseBoolean(String.valueOf(value));
    }
}
