package me.sebz.mu.pbl5;

import static com.codename1.ui.CN.*;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class MemoryLens extends Lifecycle {
    private static String sessionToken;
    private static Long familyGroupId;

    public static String getSessionToken() {
        return sessionToken;
    }

    public static void setSessionToken(String token) {
        sessionToken = token;
    }

    public static Long getFamilyGroupId() {
        return familyGroupId;
    }

    public static void setFamilyGroupId(Long id) {
        familyGroupId = id;
    }

    @Override
    public void runApp() {
        showLoginScreen();
    }

    public static void logout() {
        showLoginScreen();
    }

    public static void showLoginScreen() {
        Form loginForm = new Form("Login", new BorderLayout());

        Container center = new Container(BoxLayout.y());
        center.setScrollableY(true);
        center.getAllStyles().setPadding(10, 10, 10, 10);

        Label title = new Label("MemoryLens");
        title.setUIID("Title");
        title.getAllStyles().setAlignment(Component.CENTER);
        title.getAllStyles().setMarginBottom(10);

        TextField emailField = new TextField("", "Email", 20, TextField.EMAILADDR);
        emailField.setUIID("TextField");

        TextField passwordField = new TextField("", "Password", 20, TextField.PASSWORD);
        passwordField.setUIID("TextField");

        Button loginButton = new Button("Login");
        loginButton.setMaterialIcon(FontImage.MATERIAL_LOGIN, 5);

        Button registerButton = new Button("Register");
        registerButton.setUIID("ButtonSecondary");
        registerButton.setMaterialIcon(FontImage.MATERIAL_PERSON_ADD, 5);
        registerButton.addActionListener(e -> new RegistrationForm().show());

        loginButton.addActionListener(e -> {
            String email = emailField.getText();
            String password = passwordField.getText();

            if (email.isEmpty() || password.isEmpty()) {
                Dialog.show("Error", "Please fill all fields", "OK", null);
                return;
            }

            if (!email.contains("@") || !email.contains(".")) {
                Dialog.show("Invalid Email", "Please enter a valid email address", "OK", null);
                return;
            }

            // Real Login API Call via Node-RED
            java.util.Map<String, Object> loginData = new java.util.HashMap<>();
            loginData.put("email", email);
            loginData.put("password", password);

            GenericNetworkService.getInstance().post("/api/auth/login", loginData,
                    new GenericNetworkService.NetworkCallback() {
                        @Override
                        public void onSuccess(java.util.Map<String, Object> response) {
                            String roleShort = String.valueOf(response.get("role"));
                            String token = (String) response.get("session");
                            Object fgIdObj = response.get("familyGroupId");
                            Long fgId = (fgIdObj instanceof Number) ? ((Number) fgIdObj).longValue() : null;

                            MemoryLens.setSessionToken(token);
                            MemoryLens.setFamilyGroupId(fgId);

                            Display.getInstance().callSerially(() -> {
                                if (fgId == null) {
                                    new GroupOnboardingForm().show();
                                    return;
                                }

                                if ("0".equals(roleShort) || "ADMIN".equalsIgnoreCase(roleShort)) {
                                    new AdminDashboard().show();
                                } else if ("1".equals(roleShort) || "PATIENT".equalsIgnoreCase(roleShort)) {
                                    new PatientDashboard().show();
                                } else if ("2".equals(roleShort) || "MEMBER".equalsIgnoreCase(roleShort)
                                        || "FAMILY".equalsIgnoreCase(roleShort)) {
                                    new FamilyDashboard().show();
                                } else {
                                    Dialog.show("Error", "Unknown Role: " + roleShort, "OK", null);
                                }
                            });
                        }

                        @Override
                        public void onFailure(String errorMessage) {
                            Display.getInstance().callSerially(() -> {
                                Dialog.show("Login Failed", errorMessage, "OK", null);
                            });
                        }
                    });
        });

        center.add(title);
        center.add(new Label("Welcome Back"));
        center.add(emailField);
        center.add(passwordField);
        center.add(loginButton);
        center.add(registerButton);

        loginForm.add(BorderLayout.CENTER, center);
        loginForm.show();
    }
}
